### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by haochile01** [naiveHobo/InvoiceNet#104]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/haochile/opt/miniconda3/envs/invoicenet/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/haochile/Documents/pythonProject1/InvoiceNet/invoicenet/gui/trainer.py", line 393, in _prepare_data
    ngrams = util.create_ngrams(page, height=height, width=width)
  File "/Users/haochile/Documents/pythonProject1/InvoiceNet/invoicenet/common/util.py", line 195, in create_ngrams
    lines = divide_into_lines(words, height=img.size[1], width=img.size[0])
  File "/Users/haochile/Documents/pythonProject1/InvoiceNet/invoicenet/common/util.py", line 172, in divide_into_lines
    cur = words[1]
IndexError: list index out of range

I am so grateful that you @naiveHobo created this project. I'm really excited and interested in it. If successful (I mean I can run it) it will help my work so much.
I'm getting this error now, can anyone help me fix it? Thank you

**Comment by haochile01** [comment]
I'm still fixing it, but it's nohope

**Comment by gempain** [comment]
Related to #15
