### ISSUE TITLE
"List index out of range"

### ISSUE THREAD

**Issue by nicolas-gervais** [naiveHobo/InvoiceNet#15]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\nicol\anaconda3\envs\tf\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\nicol\Documents\InvoiceNet\invoicenet\gui\trainer.py", line 371, in _prepare_data
    ngrams = util.create_ngrams(page)
  File "C:\Users\nicol\Documents\InvoiceNet\invoicenet\common\util.py", line 118, in create_ngrams
    words = extract_words(img)
  File "C:\Users\nicol\Documents\InvoiceNet\invoicenet\common\util.py", line 91, in extract_words
    for i in range(n_boxes) if data['text'][i]]
  File "C:\Users\nicol\Documents\InvoiceNet\invoicenet\common\util.py", line 91, in <listcomp>
    for i in range(n_boxes) if data['text'][i]]
IndexError: list index out of range
```
I'm guessing this happens when there is no Tesseract result, or when the result is an empty string. When I print data, some are empty strings, which equates to False:

> 'kdakdlasd', '', 'sdsdasas'

**Comment by naiveHobo** [comment]
Do you mind sharing the document you get this error for? Would be helpful in tracking down the bug and fixing it.

**Comment by nicolas-gervais** [comment]
Thanks for your answer. Unfortunately, I can't, it's confidential data. What I can tell you is the `data` dictionary has elements of varying shape and my guess is that it's what causes an error. The `len` of `data['level']` is not necessary equal to the other dictionary elements. I tested that hypothesis and I can confirm it; Try it:
```
def extract_words(img):
    data = pytesseract.image_to_data(img, output_type=Output.DICT)
    n_boxes = len(data['level']) 

    assert len(set(map(len, data.values()))) == 1 # ADD THIS HERE
    
    words = [{'text': data['text'][i],
              'left': data['left'][i],
              'top': data['top'][i],
              'right': data['left'][i] + data['width'][i],
              'bottom': data['top'][i] + data['height'][i]}
             for i in range(n_boxes) if data['text'][i]]
    return words
```
That `assert` statement failed for me

**Comment by nicolas-gervais** [comment]
For now, I did this, but I can't guarantee that the results are good. I really don't know what that means on Tesseract's end.
```
def extract_words(img):
    data = pytesseract.image_to_data(img, output_type=Output.DICT)
    # print(list(map(len, data.values())))
    n_boxes = len(data['level']) # len(list(set(data['level'])))
    # print('nboxes', n_boxes)
    # assert len(set(map(len, data.values()))) == 1
    words = [{'text': data['text'][i],
              'left': data['left'][i],
              'top': data['top'][i],
              'right': data['left'][i] + data['width'][i],
              'bottom': data['top'][i] + data['height'][i]}
             for i in range(n_boxes - 1) if data['text'][i]] # LITTLE CHANGE HERE
    return words
```

**Comment by naiveHobo** [comment]
I tested over 10000 documents and I never saw this problem, so I can't really say what caused this. But that's right, the `extract_words` method needs to be configured such that it can extract each word along with its bounding box coordinates. I'll try to find some more unconventional documents to see if I can reproduce this issue.

**Comment by JamesChow66** [comment]
I am having the same issue

**Comment by JamesChow66** [comment]
> For now, I did this, but I can't guarantee that the results are good. I really don't know what that means on Tesseract's end.
> 
> ```
> def extract_words(img):
>     data = pytesseract.image_to_data(img, output_type=Output.DICT)
>     # print(list(map(len, data.values())))
>     n_boxes = len(data['level']) # len(list(set(data['level'])))
>     # print('nboxes', n_boxes)
>     # assert len(set(map(len, data.values()))) == 1
>     words = [{'text': data['text'][i],
>               'left': data['left'][i],
>               'top': data['top'][i],
>               'right': data['left'][i] + data['width'][i],
>               'bottom': data['top'][i] + data['height'][i]}
>              for i in range(n_boxes - 1) if data['text'][i]] # LITTLE CHANGE HERE
>     return words
> ```

Hey man, I am having the same issue here. I am not sure if your docs were scanned as well, but my guess is that the dpi of my docs is lower than 300, which cause Tesseract to generate empty results.

**Comment by gempain** [comment]
I'm having this issue as well when working with receipts instead of invoices.
