### ISSUE TITLE
Training cannot Run

### ISSUE THREAD

**Issue by michaelws92** [naiveHobo/InvoiceNet#32]
Hi, 

I need your help because I got below message error, every time I tried to run the training. Is there any miss-step that can lead to this problem? 
```python
Traceback (most recent call last):
  File "C:\Users\micha\.conda\envs\invoicenet\lib\site-packages\tensorflow\python\eager\context.py", line 2102, in execution_mode
    yield
  File "C:\Users\micha\.conda\envs\invoicenet\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\micha\.conda\envs\invoicenet\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\micha\.conda\envs\invoicenet\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]
```

**Comment by naiveHobo** [comment]
What is the dataset size you're training on? What's the validation dataset size? What's the batch size you used for training? This error usually occurs if your training data size is smaller than the batch size. Did you prepare you dataset before training?

**Comment by DelphiGeek** [comment]
Hi
Got the Same Error. I prepare the training with 4 documents (Pdf with Json). Batch Size is 4. Prepare Data works. When i click training, i got this error.

**Comment by seahsky2** [comment]
I got the same error too after i clicked start training
I've prepared 1 set of data (1 .pdf + 1.json) and set the Batch Size to 1. This is what the log shows in UI when i clicked "Prepare Data"

Total: 1
Training: 1
Validation: 0
Preparing train data...
Preparing val data...
Prepared data stored in 'processed_data/'

**Comment by seahsky2** [comment]
I was able to solve this by increasing the numbers of my training data. The training runs fine with 10 sets of data (10 .pdf + 10 .json)
