### ISSUE TITLE
tensorflow.python.framework.errors_impl.OutOfRangeError

### ISSUE THREAD

**Issue by saurabhjha21** [naiveHobo/InvoiceNet#46]
File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/home/saurabh/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 67, in <module>
    main()
  File "train.py", line 62, in main
    early_stop_steps=args.early_stop_steps
  File "/home/saurabh/Documents/InvoiceNet-master/invoicenet/common/trainer.py", line 44, in train
    train_loss = model.train_step(next(train_iter))
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/home/saurabh/Documents/InvoiceNet-master/env/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 774, in next
    raise StopIteration
StopIteration

**Comment by fedearmando** [comment]
I was able to resolve this by increasing my training data, The training runs with 10 sets (10 .pdf + 10 .json)

**Comment by fedearmando** [comment]
Also verify that the number of files distributed to the train and val folders are correct.

**Comment by darsh169** [comment]
what was the trend on decrease in loss? I am training on 400 docs and my loss is ranging between 4.6-3.75
