### ISSUE TITLE
create_ngrams() missing 2 required positional arguments: 'height' and 'width'

### ISSUE THREAD

**Issue by ksajan** [naiveHobo/InvoiceNet#57]
```
Restoring all ./models/invoicenet/order_id/best...
Exception: train_data/invoice1.pdf : create_ngrams() missing 2 required positional arguments: 'height' and 'width'

Filename: invoice1.json
Traceback (most recent call last):
  File "predict.py", line 97, in <module>
    main()
  File "predict.py", line 88, in main
    labels[field] = predictions[field][idx]
IndexError: list index out of range
```

I am getting this error when I am trying to predict after training over my invoices. What does it mean. And how I can resolve this issue?

**Comment by ksajan** [comment]
Resolved the error was a small bug in the code.
