### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by fturiot** [naiveHobo/InvoiceNet#89]
./install.sh: ligne 7: virtualenv : commande introuvable
./install.sh: ligne 8: env/bin/activate: Aucun fichier ou dossier de ce type
Processing /home/triax/projects/modules/InvoiceNet
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.

**Comment by test2a** [comment]
`python3 trainer.py`
`
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "trainer.py", line 22, in <module>
    from invoicenet.gui.trainer import Trainer
  File "/home/user/InvoiceNet/invoicenet/gui/trainer.py", line 32, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
`

`python trainer.py`
`Traceback (most recent call last):
  File "trainer.py", line 21, in <module>
    from tkinter import Tk
ImportError: No module named tkinter
`

i am facing the same issues, unable to run anything

**Comment by test2a** [comment]
ok. i used https://stackoverflow.com/questions/56155627/requestsdependencywarning-urllib3-1-25-2-or-chardet-3-0-4-doesnt-match-a-s
and `pip3 install --upgrade requests`

but now i get something new
`python3 trainer.py
Traceback (most recent call last):
  File "trainer.py", line 22, in <module>
    from invoicenet.gui.trainer import Trainer
  File "/home/user/InvoiceNet/invoicenet/gui/trainer.py", line 32, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)`

which i solved by doing `sudo apt-get install python3-pil.imagetk`

and now new error
 `python3 trainer.py
Traceback (most recent call last):
  File "trainer.py", line 22, in <module>
    from invoicenet.gui.trainer import Trainer
  File "/home/user/InvoiceNet/invoicenet/gui/trainer.py", line 35, in <module>
    from ..common import util
  File "/home/user/InvoiceNet/invoicenet/common/util.py", line 32, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'`

i used `pip3 install google-api-python-client`


this got me 

` python3 trainer.py
Traceback (most recent call last):
  File "trainer.py", line 22, in <module>
    from invoicenet.gui.trainer import Trainer
  File "/home/user/InvoiceNet/invoicenet/gui/trainer.py", line 35, in <module>
    from ..common import util
  File "/home/user/InvoiceNet/invoicenet/common/util.py", line 34, in <module>
    from google.cloud import vision
ModuleNotFoundError: No module named 'google.cloud'`

then i used `sudo pip3 install google-cloud-vision
`

now it works.  @naivehobo is this something that needs to be updated in requirements or dependencies?

**Comment by DavidBuyCo** [comment]
same here when a run data training

```
(env) ➜  InvoiceNet git:(master) ✗ python prepare_data.py --data_dir train_data/
Traceback (most recent call last):
  File "prepare_data.py", line 30, in <module>
    from invoicenet.common import util
  File "/home/david/dev-test/InvoiceNet/invoicenet/common/util.py", line 32, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
```
